//
//  FeedInterfaces.swift
//  SimpleNews
//
//  Created by Levente Vig on 2020. 11. 30..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FeedWireframeInterface: WireframeInterface {
}

protocol FeedViewInterface: ViewInterface {
}

protocol FeedPresenterInterface: PresenterInterface {
}

protocol FeedInteractorInterface: InteractorInterface {
}
