//
//  FeedInterfaces.swift
//  SimpleNews
//
//  Created by Levente Vig on 2020. 11. 30..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FeedWireframeInterface: WireframeInterface {
}

protocol FeedViewInterface: ViewInterface {
    func reload()
}

protocol FeedPresenterInterface: PresenterInterface {
    func numberOfSections() -> Int
    func numberOfItems(in section: Int) -> Int
    func itemAt(indexPath: IndexPath) -> NewsArticle
    
    func didSelectItemAt(indexPath: IndexPath)
}

protocol FeedInteractorInterface: InteractorInterface {
    func getNews(completion: NewsArticlesLoaded?)
}
