//
//  FeedPresenter.swift
//  SimpleNews
//
//  Created by Levente Vig on 2020. 11. 30..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedPresenter {

    // MARK: - Private properties -

    private unowned let view: FeedViewInterface
    private let interactor: FeedInteractorInterface
    private let wireframe: FeedWireframeInterface

    // MARK: - Lifecycle -

    init(view: FeedViewInterface, interactor: FeedInteractorInterface, wireframe: FeedWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension FeedPresenter: FeedPresenterInterface {
}
