//
//  FeedViewController.swift
//  SimpleNews
//
//  Created by Levente Vig on 2020. 11. 30..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedViewController: BaseTabbarProtocolController {

    // MARK: - Public properties -
    
    override var tabbarTitle: String? { "Feed".localized }
    override var tabbarImage: UIImage? { UIImage(systemName: "list.dash") }
    override var selectedTabbarImage: UIImage? { UIImage(systemName: "list.dash")?.withTintColor(.black, renderingMode: .alwaysOriginal) }

    var presenter: FeedPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension FeedViewController: FeedViewInterface {
}
