//
//  AboutInterfaces.swift
//  SimpleNews
//
//  Created by Levente Vig on 2020. 11. 30..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol AboutWireframeInterface: WireframeInterface {
}

protocol AboutViewInterface: ViewInterface {
}

protocol AboutPresenterInterface: PresenterInterface {
}

protocol AboutInteractorInterface: InteractorInterface {
}
