//
//  AboutPresenter.swift
//  SimpleNews
//
//  Created by Levente Vig on 2020. 11. 30..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AboutPresenter {

    // MARK: - Private properties -

    private unowned let view: AboutViewInterface
    private let interactor: AboutInteractorInterface
    private let wireframe: AboutWireframeInterface

    // MARK: - Lifecycle -

    init(view: AboutViewInterface, interactor: AboutInteractorInterface, wireframe: AboutWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension AboutPresenter: AboutPresenterInterface {
}
