//
//  DetailInterfaces.swift
//  SimpleNews
//
//  Created by Levente Vig on 2020. 12. 06..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DetailWireframeInterface: WireframeInterface {
    func open(url: String?)
}

protocol DetailViewInterface: ViewInterface {
    func bind(model: NewsArticle)
}

protocol DetailPresenterInterface: PresenterInterface {
    func readButtonTapped()
    func bookmarkButtonTapped(isOn: Bool)
}

protocol DetailInteractorInterface: InteractorInterface {
}
