//
//  DetailWireframe.swift
//  SimpleNews
//
//  Created by Levente Vig on 2020. 12. 06..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import SafariServices
import UIKit

final class DetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(model: NewsArticle) {
        let moduleViewController = DetailViewController()
        super.init(viewController: moduleViewController)

        let interactor = DetailInteractor()
        let presenter = DetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self, article: model)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailWireframe: DetailWireframeInterface {
    func open(url: String?) {
        guard let urlString = url, let safeUrl = URL(string: urlString) else {
            log.debug("url is nil or wrong")
            return
        }
        
        let safari = SFSafariViewController(url: safeUrl)
        safari.preferredControlTintColor = .mainTintColor
        navigationController?.present(safari, animated: true, completion: nil)
    }
}
