//
//  DetailInteractor.swift
//  SimpleNews
//
//  Created by Levente Vig on 2020. 12. 06..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailInteractor {
}

// MARK: - Extensions -

extension DetailInteractor: DetailInteractorInterface {
}
